export default {
  THEME_CHANGE: 'THEME_CHANGE',
  THEME_INIT: 'THEME_INIT',
  THEME_INIT_DATA: 'THEME_INIT_DATA',

  // 列表刷新--最热
  POPULAR_REFRESH: "POPULAR_REFRESH",
  // 列表加载失败
  POPULAR_REFRESH_FAIL: "POPULAR_REFRESH_FAIL",
  // 列表加载成功
  POPULAR_REFRESH_SUCCESS: "POPULAR_REFRESH_SUCCESS",
  // 列表加载更多成功
  POPULAR_LOAD_MORE_SUCCESS: "POPULAR_LOAD_MORE_SUCCESS",
  // 列表加载更多失败
  POPULAR_LOAD_MORE_FAIL: "POPULAR_LOAD_MORE_FAIL",

  // 列表刷新--趋势
  TRENDING_REFRESH: "TRENDING_REFRESH",
  // 列表加载失败
  TRENDING_REFRESH_FAIL: "TRENDING_REFRESH_FAIL",
  // 列表加载成功
  TRENDING_REFRESH_SUCCESS: "TRENDING_REFRESH_SUCCESS",
  // 列表加载更多成功
  TRENDING_LOAD_MORE_SUCCESS: "TRENDING_LOAD_MORE_SUCCESS",
  // 列表加载更多失败
  TRENDING_LOAD_MORE_FAIL: "TRENDING_LOAD_MORE_FAIL",

  // 获取列表数据--收藏
  FAVORITE_LOAD_DATA: "FAVORITE_LOAD_DATA",
  // 列表获取成功
  FAVORITE_LOAD_SUCCESS: "FAVORITE_LOAD_SUCCESS",
  // 列表获取失败
  FAVORITE_LOAD_FAIL: "FAVORITE_LOAD_FAIL",

  // 收藏状态--最热
  FLUSH_POPULAR_FAVORITE: 'FLUSH_POPULAR_FAVORITE',
  // 收藏状态--趋势
  FLUSH_TRENDING_FAVORITE: 'FLUSH_TRENDING_FAVORITE',

  // 获取语言或标签-- 最热 趋势
  LANGUAGE_LOAD_SUCCESS: 'LANGUAGE_LOAD_SUCCESS',

  // 搜索功能--加载更多成功
  SEARCH_LOAD_MORE_SUCCESS:'SEARCH_LOAD_MORE_SUCCESS',
  // 搜索功能--加载更多失败
  SEARCH_LOAD_MORE_FAIL:'SEARCH_LOAD_MORE_FAIL',
  // 搜索功能--刷新
  SEARCH_REFRESH:'SEARCH_REFRESH',
  // 搜索功能--刷新成功
  SEARCH_REFRESH_SUCCESS:'SEARCH_REFRESH_SUCCESS',
  // 搜索功能--刷新失败
  SEARCH_FAIL:'SEARCH_FAIL',
  // 搜索功能--取消
  SEARCH_CANCEL:'SEARCH_CANCEL',

}
